box-builder/box

builder/builder.go, main.go
=> builder,main.go: -t/--tag to tag the final image

builder/builder.go, builder/util_test.go, main.go
=> builder,main.go: verb/func filtering, -o/--omit flag.

Godeps/Godeps.json, Makefile, build.rb, builder/executor/docker/docker.go, cli-tests/basic_test.go, cli-tests/init_test.go, cli-tests/test.rb, docker-test.sh, vendor/github.com/erikh/testcli/README.md, vendor/github.com/erikh/testcli/main.go
=> Cli testing

Godeps/Godeps.json, builder/builder_test.go, builder/executor/docker/docker.go, builder/funcs.go, docs/functions.md, vendor/github.com/mitchellh/go-mruby/Makefile, vendor/github.com/mitchellh/go-mruby/README.md, vendor/github.com/mitchellh/go-mruby/args.go, vendor/github.com/mitchellh/go-mruby/func.go, vendor/github.com/mitchellh/go-mruby/golint.sh, vendor/github.com/mitchellh/go-mruby/gomruby.h, vendor/github.com/mitchellh/go-mruby/parser.go, vendor/github.com/mitchellh/go-mruby/value_type.go
This implements naive import statements. No path hierarchy is prescribed, just straight file paths.
@errordeveloper once merged this will be available to you in master. Docs and tests exist if you're interested in using it.
=> Import statement

builder/builder.go
=> builder: Fix a cosmetic whitespace issue

Makefile, build.rb, release/RELEASE.md, release/release.sh
=> Makefile,release: release materials

builder/builder_test.go
=> builder/builder_test.go: forgot to close all the mruby handles

Makefile, builder/executor/docker/docker.go, builder/executor/docker/docker_test.go
=> Makefile,builder/executor/docker: Add some initial docker executor tests.

README.md, docs/index.md, main.go
this adds a new "shell" synonym and updates the docs to reflect the new REPL functionality.
=> Docs + Shell synonym

builder/builder.go, builder/executor/docker/docker.go, builder/verbs.go
=> builder,builder/executor/docker: install signal handlers across the platform

builder/executor/docker/docker.go
* the tty copy seems to occasionally bug out talking over the unix socket;
something seems to be interrupting it. Now it always repeats the copy
regardless of read/write errors.
* We use the cancellable context now for all operations inside the run hook;
this should be more resilient against signals being issued while the hook is
starting.
=> builder/executor/docker: stdin-handling fixes

CHANGELOG.md, Makefile, README.md, build.rb, builder/builder_test.go, builder/config/config.go, builder/executor/docker/docker.go, builder/executor/docker/docker_image_test.go, builder/executor/docker/docker_test.go, builder/executor/docker/image.go, builder/executor/docker/pull_progress.go, builder/executor/docker/run.go, builder/funcs.go, builder/signal/signal.go, builder/verbs.go, checks.sh, docker-test.sh, docs/user-guide/verbs.md, image/image.go, image/image_test.go, log/log.go, tar/tar.go
This includes several fixes and improvements to clean up ugly code exposed by the go report card.
=> Go Report Card

builder/executor/docker/image.go
=> builder/executor/docker/image.go: Prinicipally

Godeps/Godeps.json, builder/builder.go, builder/verbs.go, repl/repl.go, vendor/github.com/mitchellh/go-mruby/context.go, vendor/github.com/mitchellh/go-mruby/gomruby.h, vendor/github.com/mitchellh/go-mruby/mruby.go
Closes #76 
Fixes #77 
This is (with appropriate mruby patches) what is necessary to fix repl multi-line input in box.
=> Repl fixes

builder/builder.go, builder/builder_test.go, builder/util_test.go, main.go, repl/repl.go
=> builder,main.go,repl: support context cancellation of statements

builder/builder.go, builder/executor/docker/docker.go, builder/executor/executor.go
=> builder,builder/executor: clean up transient images after build

builder/builder.go, builder/verbs.go
=> bulider: refactor to use BuildConfig directly in builder

copy/copy.go, main.go
=> copy,main.go: fix copy logging

Godeps/Godeps.json, vendor/github.com/mitchellh/go-mruby/args.go, vendor/github.com/mitchellh/go-mruby/func.go, vendor/github.com/mitchellh/go-mruby/gomruby.h, vendor/github.com/mitchellh/go-mruby/mruby.go, vendor/github.com/mitchellh/go-mruby/value.go
Upgrades with the patches contained in https://github.com/mitchellh/go-mruby/pull/50. Should dramatically increase stability in all functions.
=> Godeps,vendor: upgrade mitchellh/go-mruby

builder/builder_test.go, builder/executor/docker/docker_test.go, builder/verbs.go, docs/index.md, docs/user-guide/verbs.md, image/image.go, tar/tar.go, tar/tar_test.go
=> builder,tar: support .dockerignore files and new copy arguments to handle ignore lists.

Makefile
=> Makefile: fix build ordering during release process

builder/config/config.go, builder/verbs.go, docs/user-guide/verbs.md
=> From scratch

builder/copy.go, builder/executor/docker/docker.go, builder/executor/executor.go, builder/util.go, builder/verbs.go, cli-tests/basic_test.go, cli-tests/run_test.go, docs/user-guide/verbs.md
=> Run statements, silenced per-line

builder/executor/docker/docker.go, builder/executor/executor.go, builder/verbs.go, main.go
=> main.go,builder: properly terminate run output in multi-mode

builder/executor/docker/docker_image_test.go, multi/multi_test.go
The tests are broken due to the image changes in the no-ubuntu PR. This should fix it.
=> Fix the tests

builder/builder_test.go, builder/config/config.go, builder/copy.go
Would love to hear some short opinions on this change if people have time!
=> Allow copying files into volumes by removing volumes from the configuration

tar/archive.go, tar/sum.go, tar/tar_test.go, tar/unarchive.go
This is just some generic code to start working towards runc progress (#10). It
will allow us to unarchive into the overlayfs stacked filesystems.
=> Unarchiving code

builder/builder.go, builder/builder_test.go, builder/config/config.go, builder/executor/docker/docker.go, builder/executor/docker/docker_image_test.go, builder/executor/docker/image.go, builder/executor/executor.go, builder/verbs.go, copy/copy.go, logger/logger.go, multi/multi_test.go
Fixes #122
This resolves several testing issues and the multi-mode issue above.
cc @Xe
=> Fix Multi-Mode Output (and a few other things)

builder/builder_test.go, builder/copy.go
=> builder: fix globbing, tests included.

builder/builder.go, multi/multi.go
=> Fix Multi-Mode filename propagation

builder/executor/docker/docker.go, builder/executor/docker/run.go
=> Cleanup runs after a ^C or SIGTERM

release/release.sh
=> Integrate .deb and .rpm packaging

layers/docker.go
=> layers: remove a couple of newlines and formatting that was bugging out non-tty pull output

README.md
=> Update build instructions to incorporate new package requirements

builder/verbs.go, image/image.go, logger/logger.go
=> builder,image,logger: some cosmetics around flatten output

builder/builder_test.go, builder/config/config.go, builder/verbs.go, docs/user-guide/verbs.md
cc @errordeveloper
Fixes #144 
Design ok?
=> Label Verb

build.rb
=> build.rb: trim verbose unpacking output in build plan

build.rb
=> build.rb: install pip directly to fix errors

build.rb
=> build.rb: silence curl for pip command

builder/builder.go, builder/config/config.go, builder/executor/docker/docker.go, builder/executor/docker/docker_image_test.go, builder/executor/docker/docker_test.go, builder/executor/docker/run.go, fetcher/fetcher.go, layers/docker.go, layers/docker_image.go, layers/docker_test.go, layers/types.go
This package augments the new layers package with a fetcher package which can
fetch images from remtoe sources.
=> New fetcher package for fetching and locating images

builder/builder_test.go, builder/funcs.go, builder/util_test.go, layers/docker_image.go, layers/types.go, logger/logger.go, tar/archive.go
Some small commits around the new save feature and some tests.
=> More refactors 

builder/builder_test.go, builder/funcs.go, docs/user-guide/functions.md, layers/docker_image.go, layers/types.go, tar/archive.go
This implements OCI image export through the `save` function.
=> Save to OCI

README.md
=> README.md: update build status link to reflect new jenkins

docs/build-plans.md, docs/index.md, docs/user-guide/functions.md, mkdocs.yml
=> New Documentation

README.md
This is just a small readme update to change the video for the front page.
=> Update box video in README

logger/logger.go
=> Fix justification in progress meters

Makefile
=> Fix early termination in makefile

install.sh.tmpl, release/release.sh
=> basic installer script, needed release.sh change

README.md, build.rb
=> Small fixups

install.sh.tmpl
Wrapped destructive code in a function to protect against bad
things happening on a partial download of the installer.
=> Safer installer

builder/builder_test.go, builder/config/config.go, builder/util.go, builder/verbs.go, docs/user-guide/verbs.md, multi/multi_test.go
=> Entrypoint cmd

docs/index.md
=> docs: update with instructions to use installer

install.sh, install.sh.tmpl
This fixes an issue with users who do not have sudo but attempt to install as root.
=> Fix installer

repl/repl.go
=> repl: enable color mode in repl

README.md
=> README.md: fix links in readme

README.md
=> README.md: center README image

repl/repl.go
=> repl: do not show a multiline error on anything but parser errors.

docs-theme/css/base.css, docs-theme/css/highlight.css
=> change highlighter to use solarized theme

checks.sh, layers/docker.go, main.go, repl/repl.go
=> repl: rewrite; handle several situations in non-tty mode

builder/executor/docker/run.go
=> builder/executor/docker: handle terminals appropriate during debug mode

builder/evaluator/evaluator.go, builder/evaluator/mruby/mruby.go, main.go, repl/repl.go
* fix --no-trim
* confirmation message in repl after a command completes
=> Small fixes

repl/repl.go
=> Reset & Help commands

cli-tests/basic_test.go, docs/index.md, main.go
=> box.rb as default filename

repl/repl.go
=> repl: print help immediately on repl start

Makefile
=> Makefile: add a task to update erikh.githubn.com/box

builder/builder_test.go
This PR fixes issues related to the Cmd. The debian image has a different Cmd now and this is causing issues. These changes modify the tests to ensure that the Cmd of the parent image propagates properly.
=> builder/builder_test.go: fix Cmd for tests

box.rb
=> box.rb: bump Go to 1.8.3

portable.sh.tmpl
=> portable.sh.tmpl: fix escape protection
