builder/builder.go

Since they are a part of the command, a duplicate hash provided by a different
command has the potential to corrupt the cache accidentally.

builder: do not hash cache keys

---

builder/builder.go
builder/executor/docker/docker.go
builder/signal/signal.go
builder/verbs.go
cli-tests/basic_test.go
main.go
tar/tar.go

This introduces a package called `builder/signal`, which implements generic
signal handling with hooks. Installed hooks in several places to perform
cleanup.
Fixes #49 

builder: better signal handling

---

Godeps/Godeps.json
builder/builder.go
vendor/github.com/mitchellh/go-mruby/README.md
vendor/github.com/mitchellh/go-mruby/gomruby.h
vendor/github.com/mitchellh/go-mruby/mruby.go
vendor/github.com/mitchellh/go-mruby/value.go

This turns off gc so that functions will no longer accidentally access dead objects. This is a temporary measure until go-mruby's API supports measures to detect if an object is dead safely before converting it to a given type.

Turn off gc

---

builder/builder_test.go
builder/config/config.go
builder/executor/docker/docker.go
builder/executor/docker/docker_run_test.go
builder/util_test.go
builder/verbs.go
docs/user-guide/verbs.md

* New state management tracks temporary needs and inheritance alongside each
other to separate powers, making it much easier to track state within the
application itself.
the result of this is:
* no longer clears cmd when entrypoint is used
* inheritance works properly every time
* code is much cleaner
Fixes #56

builder: correct a number of issues with cmd/entrypoint:

---

build.rb
builder/builder.go
builder/builder_test.go
builder/config/config.go
builder/verbs.go
main.go
repl/repl.go

builder,main.go,repl: Remove final commit logic from the code.
This behavior was the cause of a lot of confusion around the design and
implementation of the builder itself. It lead to more problems than it solved
and was largely a workaround for the problems with state fixed in
0de072a9004c113e9b1d2b87471345e902b9399e.

Remove final commit

---

builder/builder_test.go
builder/config/config.go
builder/util_test.go
builder/verbs.go

builder: fix copy routines that used relative paths with workdir.

---

builder/builder_test.go
builder/executor/docker/docker.go
builder/verbs.go
docs/user-guide/verbs.md

Prior to this patch, copying a file over a dir meant that the dir would be
removed, uploading the file in its place.
Now, this aborts the run. To copy the file INTO the dir, specify it with `/` at
the end.
Documentation has also been amended.
Fixes #69 
cc @errordeveloper

builder,docs: fix copy semantics

---

builder/builder_test.go
builder/config/config.go
builder/testdata/dockerfiles/Dockerfile.volumes
builder/verbs.go

builder: (temporarily) do not allow copies into volumes

---

repl/repl.go

I've not seen this happen with box for real, but experimenting with code that's based on this, I realised it'd be good idea to make sure errors are handled here and whoever hacks on this in the future doesn't see a silent crash with a surprisingly positive return code.

Do not abort so quietly

---

builder/builder_test.go
builder/verbs.go
docs/user-guide/verbs.md

workdir and inside didn't really cooperate in the sense that they keyed
off each other. Now this works:
```ruby
workdir "/etc"
inside "apt" do
run "rm sources.list"
end
```

builder: make inside relative to workdir.

---

builder/builder_test.go
builder/verbs.go
tar/tar.go
tar/tar_test.go

* now, if you supply a relative directory path, it will not rewrite
symlinks to have an additional path component.
* symlinks are no longer linked to the wrong places, and symlinks are no
longer capable of following under the working directory.

builder,tar: fix a number of issues with the copy statement.

---

builder/builder.go
builder/executor/docker/docker.go
builder/executor/executor.go
builder/util_test.go
builder/verbs.go
main.go
repl/repl.go

Additionally some issues with the REPL were fixed:
* The `-o` flag is now respected
* Caching is turned off, which makes the REPL much easier to use.

builder,repl,main.go: Refactors to support better configuration.

---

Makefile
builder/builder.go
builder/builder_test.go
builder/executor/docker/docker.go
builder/executor/docker/docker_image_test.go
builder/executor/docker/docker_run_test.go
builder/executor/docker/docker_test.go
builder/executor/docker/run.go
builder/funcs.go
builder/util_test.go
main.go
multi/multi.go
multi/multi_test.go
repl/repl.go

Here we go! This is the first edition of the multi-builder, a way to build docker images in parallel.
The initial implementation is a (large) thread safety patch for the builder and the new 'multi' package, which is used to facilitate the multi-building. Then it is linked into the binary via the `multi` command which lets you specify multiple plans.
The UI is still coming and that will be a separate patch.

multi,main.go,builder: first edition of multi-builder.

---

cli-tests/basic_test.go
main.go

main.go: fix usage documentation (instead of a panic) on invocation without args.

---

build.rb

This bumps Docker to 1.12.5. This version fixes some bugs introduced by 1.12.4.

build.rb: bump Docker to 1.12.5

---

builder/verbs.go

This patch fixes the handling of output after it has been switched off in the
DSL, it would fail to come back on.

Handle output after turning output off

---

builder/executor/docker/docker_image_test.go
builder/executor/docker/docker_test.go
multi/multi_test.go

This PR eliminates the need for the ubuntu image in the test suite. It was
large and frequently was a part of the no space errors on travis.

Do not use ubuntu image

---

build.rb
builder/builder.go
builder/builder_test.go
builder/verbs.go

This enables post build hooks, like so:[
```ruby
from "golang"
after do
flatten
tag "test"
end
skip do
run "ls /"
end
```
This will produce a flattened equivalent to the `golang` image.

Enable post-build hooks

---

builder/builder_test.go
builder/verbs.go

This bug is caused by a lack of overwrite operation for duplicate values in the
environment.
Example:
```ruby
from "debian" # sets $PATH
env PATH: "/test"
```
This will set the PATH as the debian image prescribes it PLUS the other PATH in
the build plan, and the first one will win.

Do not only append to environment

---

Makefile
build.rb

This changes the build to use the debian image and the after hooks to tag
erikh/box:master. This allows us to create a two layer image which is much
smaller than the golang base image we were using before.

Change build to use debian image

---

tar/tar.go

The tar routines would warning via docker/docker/pkg/archive when specifying
files and an includeList (which we primed with just the file). This omits the
includeList creation so the warning does not occur.

Fix tar routines to not warn when copying files (not directories)

---

.gitignore
release/release.sh

Version in main.go was being edited inappropriately and leaving stale files around on BSD sed.

Fix release materials

---

build.rb
release/release.sh

This upgrades the docker client and engine to use the latest, 1.13.1.

Upgrade docker client and reference server for testing

---

pull/pull.go

This is just a patch to fix a regression from the port to containers/image and
earlier refactors.

Restore pull progress meter in from statements

---

builder/copy.go
builder/executor/docker/docker_test.go
builder/verbs.go
copy/copy.go
image/image.go
image/image_test.go
layers/docker.go
layers/docker_image.go
logger/logger.go
tar/archive.go
tar/sum.go
tar/tar_test.go

builder,copy,image,layers,logger,tar: Improve progress meters.
This adds the progress meter display code to logger.Logger where it
belongs and integrates it with copy.WithProgress.

Fix progress meters, integrate with containers/image

---

build.rb

Go 1.8 includes a lot of fixes and performance improvements. The overhead of calling C functions from Go has been reduced to about half of what it used to be before. The overhead of defer calls has also been lowered to about half.

build.rb: bump Go to 1.8

---

Makefile

The builder tests in particular are very long and are the first tests run.
This will allow tests that would normally fail later in the cycle to be
able to fail much earlier giving quicker feedback.

Reorder tests

---

docker-test.sh

This also fixes some long-standing hanging bugs when the tests terminated
earlier than anticipated.

Mute docker output in tests

---

builder/verbs.go
image/image.go
main.go
repl/repl.go
signal/signal.go
tar/archive.go

This makes the signal handler a singleton (for simplicity) and also makes
temporary files amenable to cleanup when handlers fire.

Refactor signal handling

---

builder/builder_test.go
builder/funcs.go
docs/user-guide/functions.md

Fixes #165
Note that this new save function does not create a new layer, this is
(forgotten by me) different with the tag verb which does. I may leave the tag
verb alone now because of this and add the save verb which operates slightly
different and will combine parameters to form one function. This is
instrinsically different than tag which just saves a layer to docker.

builder: save function

---

tar/archive.go
tar/tar_test.go

tar: remove the limitation on symlinks that fall below the target WD.
This was causing a lot of problems and would make shipping symlinks that
were linked to a lower dir (/etc for example) inside the container. I
think that even though there are some security concerns, this is a
better, more flexible option for users.

Fix symlinks in archive routines

---

builder/builder_test.go
builder/funcs.go
docs/user-guide/functions.md
layers/docker_image.go
layers/types.go

This allows for the saving of images to files. This is critical for initial OCI
support.

Save to file

---

build.rb

This will be needed until Go 1.8.1 is out. I haven't run into any actual issues so far. It's better to stick to 1.7.5 in the meantime.

build.rb: downgrade Go to 1.7.5

---

builder/executor/docker/docker.go
layers/docker_image.go
layers/types.go
repl/repl.go
signal/signal.go

Currently, run statements do not echo output when running in the repl due to an
architectural change in 0.4. This patch fixes that.

Fix REPL run output

---

docker-test.sh

Timeouts were not affecting the build process properly, not exiting
non-zero. Additionally the timeout needed to be increased now that
tests take longer.

Increase test timeout

---

fetcher/fetcher.go
layers/docker.go
logger/logger.go
multi/multi_test.go

This contains a few fixes for situations where the tty is not present:
* Editing would output numerous newlines when in non-tty mode
* Output writing was not all going through the logger, which made testing output harder.

Fix non-tty output

---

builder/builder_test.go

This test was testing for the presence of a file named `*` which was
errorneously expanding in the shell, causing an error which allowed the test to
succeed, but for the wrong reasons.

Fix a test that was failing for the wrong reasons

---

.gitignore
Makefile
build.rb
docker-test.sh
portable.sh.tmpl
release/release.sh

This modifies the build to no longer template `main.go`, leveraging ldflags
to both set the version and build static binaries. This allows
cross-distribution packaging and allows us to deliver a more complete
experience in the docker image, which OS X needs now that we're bound to
linux dependencies.

Makefile,build.rb,release: Convert to static build, move away from OS X

---

README.md

Make install section, move it so that the usage instructions are contiguous.

README Install script instructions

---

builder/builder.go
builder/executor/docker/docker_run_test.go
builder/executor/docker/docker_test.go
docs/user-guide/cli.md
image/image.go
layers/docker_test.go
logger/logger.go
main.go
multi/multi.go
multi/multi_test.go
repl/repl.go
tar/tar_test.go

Option --no-trim to get "full" output
closes #197

Make logger trim to terminal size by default

---

builder/builder.go
builder/copy.go
builder/executor/docker/docker.go
builder/executor/docker/docker_run_test.go
builder/executor/docker/docker_test.go
builder/executor/docker/run.go
builder/executor/executor.go
builder/util_test.go
builder/verbs.go
fetcher/fetcher.go
global/global.go
layers/docker.go
layers/docker_image.go
layers/docker_test.go
layers/types.go
main.go
multi/multi_test.go
repl/repl.go

Previously these parameters were all passed on the stack causing a ton
of idiocy in the API. This simplifies the code and works towards a more
abstract design for the builder.

global: new package to manage global properties to a builder

---

Makefile
build.rb
builder/builder_test.go
builder/command/commands.go
builder/command/verbs.go

This improves the build system. It also contains a fix for a situation where tagging in an after block with skip statements, would not appropriately tag the image for use.

Build system fixes

---

build.rb

This bumps Go to 1.8.1. This version addresses the issues discovered in 1.8.0.
https://github.com/golang/go/issues?q=is%3Aissue+milestone%3AGo1.8.1+is%3Aclosed

build.rb: bump Go to 1.8.1

---

docs-theme/container-header.html

This needs some additional tooling in the release.sh script that requires a markdown rendered for the changelog, which will require some styles.
I don't have time to do that just yet, so here's a patch to blank it out for now.

docs-theme: Remove container-header (for now)

---

builder/builder_test.go
builder/command/from.go
builder/config/config.go
fetcher/fetcher.go
layers/docker.go
layers/docker_image.go
layers/docker_test.go
layers/types.go

previously, nulls would be set on the entrypoint, triggering inheritance
from `run` statments that were the previous commit in the docker chain.
What this does now is set it to `[]string` which is an empty command in
the docker configuration.
Note that there is now no way to do `entrypoint nil` in a way that will
inherit from the previous entrypoint statement, however, I don't think
this is necessarily a bad thing. :)
Fixes #232

buidler,fetcher,layers: fix cmd/entrypoint semantics

---

portable.sh.tmpl

Previously, if the user specified environment variables, they were
ignored by the portable script. This is because the environment
variables would need to have been propagated to docker that box runs in,
so it can then read the environment variables from the container.
Now, you can specify BOX_INCLUDE_ENV to whitespace-delimit environment
variables to pass from your host into the container, allowing it to be
easy to generically do this in make tasks etc.
This is a stop-gap for environment usage on OS X in particular, until
0.6.0 arrives (with real dictionaries) this feature is really
needed.
This will be backported into 0.5.4.

portable.sh.tmpl: bring in environment variables from the host

---

box.rb

This moves the build environment to golang 1.9.2.

Move to golang 1.9.2
